# fly.toml app configuration file generated for blog-list1-misty-leaf-3375 on 2025-01-05T17:56:38-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-list1-misty-leaf-3375'
primary_region = 'dfw'

[env]
  PORT = "3003" 

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
